### ISSUE TITLE
Setting quality for JPEG compression

### ISSUE THREAD

**Issue by xkacenga** [glencoesoftware/raw2ometiff#68] opened 2021-12-20 10:29 UTC
Hello,
I am trying to convert slides using JPEG compression, but I have issues with setting --quality. I found this [year old post](https://github.com/glencoesoftware/raw2ometiff/issues/26#issuecomment-730697139). Is it still impossible to set quality for JPEG compression? If yes, what is the default quality (or how is it determined)?

Thank you,
Martin

**Comment by holubp** [comment] 2023-05-12 20:03
Hi, is there any update on this? Being unable to set the quality of JPEG compression is quite disabling for many applications. Thanks!

**Comment by melissalinkert** [comment] 2023-05-15 19:23
The update to Bio-Formats 6.13.0 proposed in #103 includes https://github.com/ome/ome-codecs/pull/26, which introduced the ability to configure JPEG compression quality. As implied there, the expected quality would be between 0.25 and 1.0.

I have not yet verified that converting with `--compression JPEG --quality 0.5` (or similar) works as intended, but we should be able to include this feature in the next raw2ometiff release.

**Comment by sbesson** [comment] 2023-05-18 09:18
Closing as per https://github.com/glencoesoftware/raw2ometiff/pull/103#pullrequestreview-1432348988

**Closed by sbesson** 2023-05-18 09:18 UTC
Labels: enhancement
